---
abstract: 'more than OS fingerprinting unification'
author:
  - 'GomoR <gomor_at_networecon.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SinFP3
no_index:
  directory:
    - t
    - inc
requires:
  Class::Gomor: 0
  DBD::SQLite: 0
  DBI: 0
  Data::Dumper: 0
  Digest::MD5: 0
  File::Glob: 0
  FindBin: 0
  Frontier::Client: 0
  IO::Socket::INET: 0
  IO::Socket::INET6: 0
  LWP::UserAgent: 0
  Net::Frame: 1.07
  Net::Frame::Device: 0
  Net::Frame::Dump: 1.09
  Net::Frame::Layer::IPv6: 0
  Net::Frame::Simple: 0
  Net::Libdnet: 0.90
  Net::Netmask: 0
  Net::Write: 0
  Net::Write::Fast: 0.11
  POSIX: 0
  Parallel::ForkManager: 0
  Socket: 0
  Socket6: 0
  perl: 5.006001
version: 1.02
